GA - Yang: CPostProcessingAlg Class Reference
CPostProcessingAlg Class Reference abstract
#include "PostProcessingAlg.h"
Public Member Functions
virtual ~CPostProcessingAlg ()
virtual void Update (const std::vector< CChromosome > &iElitism)=0
bool Execute (const CGenotypeData &ioGenotypeData, int iOrder)
virtual void UpdateGenotypeData (CGenotypeData &ioGenotypeData)=0
virtual void Print (const CGenotypeData &ioGenotypeData, const std::string &iBaseFileName, int iOrder) const =0
Static Public Member Functions
static CPostProcessingAlg * CreateConcrete ()
Access to Singleton object.
Protected Member Functions
CPostProcessingAlg ()
virtual bool DerivedExecute (const CGenotypeData &ioGenotypeData, int iOrder)=0
Protected Attributes
uint64_t mNumberOfFitnessCalcualtions
Detailed Description
Definition at line 8 of file PostProcessingAlg.h.
Constructor & Destructor Documentation
virtual CPostProcessingAlg::~CPostProcessingAlg () inline virtual
Definition at line 15 of file PostProcessingAlg.h.
CPostProcessingAlg::CPostProcessingAlg () inline protected
Definition at line 26 of file PostProcessingAlg.h.
Member Function Documentation
static CPostProcessingAlg* CPostProcessingAlg::CreateConcrete () static
Access to Singleton object.
virtual bool CPostProcessingAlg::DerivedExecute (const CGenotypeData & ioGenotypeData, int iOrder) protected pure virtual
Implemented in CClusteringAlg, and CContinuityAlg.
Referenced by Execute().
bool CPostProcessingAlg::Execute (const CGenotypeData & ioGenotypeData, int iOrder) inline
Definition at line 31 of file PostProcessingAlg.h.
References DerivedExecute(), CChromosome::FitnessCalculationCounter(), and mNumberOfFitnessCalcualtions.
virtual void CPostProcessingAlg::Print (const CGenotypeData & ioGenotypeData, const std::string & iBaseFileName, int iOrder) const pure virtual
Implemented in CClusteringAlg, and CContinuityAlg.
virtual void CPostProcessingAlg::Update (const std::vector< CChromosome > & iElitism) pure virtual
Implemented in CClusteringAlg, and CContinuityAlg.
virtual void CPostProcessingAlg::UpdateGenotypeData (CGenotypeData & ioGenotypeData) pure virtual
Implemented in CClusteringAlg, and CContinuityAlg.
Member Data Documentation
uint64_t CPostProcessingAlg::mNumberOfFitnessCalcualtions protected
Definition at line 24 of file PostProcessingAlg.h.
Referenced by Execute().
The documentation for this class was generated from the following file:
PostProcessingAlg.h