#pragma once

#include "GenotypeData.h"

using namespace std;

////////////////////////////////////////////////////////////////////////
/// \brief    Concrete data set of case and controls data
///
/// Role: Concrete data set generated by http://www.hapsample.org/
///
/// Responsibilities: 
///      1. Knows how to load case and controls data from Hapmap file
///      2.	Knows how the format of Hapmap dataset 
////////////////////////////////////////////////////////////////////////
class CHapSampleData : public CGenotypeData
{
public:

    virtual bool Load() override;

    vector<string> BuildBlackList(const string &caseFileName ) const;


private:

    /// \brief    Load from file SNPs data into input collection 
    /// \param[in] fileName   File that contains cases data
    /// \param[out] dataSet   Data set of all individuals in population
    /// \param[out] totalSnp   All SNPs data
    bool LoadFile(const string& fileName, vector<vector<BYTE>>& dataSet, vector<CSnpData>& totalSnp);

    bool LoadSNP(const string& line, CSnpData& snp, vector<vector<BYTE>>& dataSet, const vector<string>& iBlackList);

    void Reorganize(const vector<pair<string,BYTE>>& barCode);
};

