#pragma once

#include "GenotypeData.h"

#include <random>
#include <memory>

using namespace std;

////////////////////////////////////////////////////////////////////////
/// \brief    Concrete data set of case and controls data
///
/// Role: Concrete data set generated by http://www.hapsample.org/
///
/// Responsibilities: 
///      1. Knows how to load case and controls data from file
////////////////////////////////////////////////////////////////////////
class CSyntheticData : public CGenotypeData
{
public:

    virtual bool Load() override;
    
private:

    void GenerateGenotype(uint32_t iEventsNum, const vector<pair<uint32_t,uint32_t>>& iBarcode, 
                          unique_ptr<bool>& ioAllocated, vector<vector<BYTE>>& ioData,  vector<CSnpData>& iTotal, 
                          default_random_engine& iRandomEngine, uniform_int_distribution<unsigned int>& iDataDistribution );
};

