GA - Yang: EvolutionaryComputing::CMatching Class Reference
EvolutionaryComputing::CMatching Class Reference
#include "Matching.h"
Classes
class CIndividualPreferences
Private Types
enum EIndividualType { eWoman = 0, eMan, eDog }
Private Member Functions
public CMatching ()
public void Init (bool init)
public uint Evaluate (uint[] iGroup)
private void BuildPreferencesData ()
public override string ToString ()
private void FromStream (StreamReader input)
Private Attributes
public const uint DATA_SIZE = 50
private CIndividualPreferences[,] mPreferences
Static Private Attributes
static public uint sMaxEvaluation = DATA_SIZE
Detailed Description
Definition at line 16 of file Matching.h.
Member Enumeration Documentation
enum EvolutionaryComputing::CMatching::EIndividualType private
Enumerator
eWoman
eMan
eDog
Definition at line 19 of file Matching.h.
Constructor & Destructor Documentation
public EvolutionaryComputing::CMatching::CMatching () inline private
Definition at line 26 of file Matching.h.
References DATA_SIZE, and mPreferences.
Member Function Documentation
private void EvolutionaryComputing::CMatching::BuildPreferencesData () inline private
Definition at line 92 of file Matching.h.
References DATA_SIZE, EvolutionaryComputing::CMatching::CIndividualPreferences::mFirstPreferences, mPreferences, and EvolutionaryComputing::CMatching::CIndividualPreferences::mSecondPreferences.
Referenced by Init().
public uint EvolutionaryComputing::CMatching::Evaluate (uint[] iGroup) inline private
Definition at line 76 of file Matching.h.
References EvolutionaryComputing::CMatching::CIndividualPreferences::mFirstPreferences, mPreferences, and EvolutionaryComputing::CMatching::CIndividualPreferences::mSecondPreferences.
private void EvolutionaryComputing::CMatching::FromStream (StreamReader input) inline private
Definition at line 156 of file Matching.h.
References DATA_SIZE, EvolutionaryComputing::CMatching::CIndividualPreferences::FromStream(), and mPreferences.
Referenced by Init().
public void EvolutionaryComputing::CMatching::Init (bool init) inline private
Definition at line 45 of file Matching.h.
References BuildPreferencesData(), FromStream(), and ToString().
public override string EvolutionaryComputing::CMatching::ToString () inline private
Definition at line 136 of file Matching.h.
References DATA_SIZE, mPreferences, and EvolutionaryComputing::CMatching::CIndividualPreferences::ToString().
Referenced by Init().
Member Data Documentation
public const uint EvolutionaryComputing::CMatching::DATA_SIZE = 50 private
Definition at line 20 of file Matching.h.
Referenced by BuildPreferencesData(), EvolutionaryComputing::CMatching::CIndividualPreferences::CIndividualPreferences(), CMatching(), FromStream(), EvolutionaryComputing::CMatching::CIndividualPreferences::FromStream(), ToString(), and EvolutionaryComputing::CMatching::CIndividualPreferences::ToString().
private CIndividualPreferences [,] EvolutionaryComputing::CMatching::mPreferences private
Definition at line 228 of file Matching.h.
Referenced by BuildPreferencesData(), CMatching(), Evaluate(), FromStream(), and ToString().
public uint EvolutionaryComputing::CMatching::sMaxEvaluation = DATA_SIZE static private
Definition at line 231 of file Matching.h.
The documentation for this class was generated from the following file:
Matching.h