GA - Yang: CChromosome Class Reference
CChromosome Class Reference
CChromosome is one element in GA population.
#include "Chromosome.h"
Public Member Functions
CChromosome ()
Empty constructor.
CChromosome (unsigned int iLength, const unsigned int *iSNPs, const BYTE *iGenotypes, double iFitness=DBL_MAX, const vector< string > &iAdditionaFitnesslInfo=vector< string >())
predefined chromosome
CChromosome (unsigned int iSNP, BYTE iGenotypes=2, double iFitness=DBL_MAX, const vector< string > &iAdditionaFitnesslInfo=vector< string >())
predefined chromosome of length 1
CChromosome (const CChromosome &input)
Copy constructor.
virtual ~CChromosome ()
Destructor.
CChromosome & operator= (const CChromosome &input)
Assignment operator.
virtual CChromosome & Assignment (const CChromosome &input)
Assignment operator.
bool operator== (const CChromosome &input) const
Comparison operator.
bool operator== (const vector< unsigned int > &input) const
bool operator< (const CChromosome &input) const
bool operator> (const CChromosome &input) const
double Fitness () const
void Fitness (double input)
unsigned int Length () const
unsigned int SNP (unsigned int index) const
unsigned int Genotype (unsigned int index) const
void SNP (unsigned int index, unsigned int iValue)
void Genotype (unsigned int index, BYTE iValue)
const unsigned int * SNP () const
BYTE * Genotype () const
const vector< string > & AdditionalFitnessData () const
Static Public Member Functions
static void Init (unsigned int iLength)
static unsigned int RequiredLength ()
static uint64_t FitnessCalculationCounter ()
Static Protected Member Functions
static void ReplaceSNP (unsigned int &c1, unsigned int &c2)
Replace the value of 2 SNPs.
static void ReplaceGenotype (BYTE &c1, BYTE &c2)
Replace the value of 2 Genotypes.
Protected Attributes
unsigned int mLength
Chromosome current length (number of SNPs)
unsigned int * mSNPs
Chromosome's SNPs.
BYTE * mGenotypes
Genotype of each SNP {1,2,3}.
double mFitness
Fitness of current object.
bool mFitenssValid
true iff the object's contents has been changed from the last fitness calculation.
vector< string > mAdditionalFitnessData
Additional Fitness information.
Static Protected Attributes
static unsigned int sLength
Chromosome required length (number of SNPs)
static uint64_t sFitenssCalculationCounter
Detailed Description
CChromosome is one element in GA population.
Role: Represents one solution (chromosome of bits). Is compounds of list of
Responsibilities:
Knows to perform crossover with another solution
Knows to perform mutation
Knows to identify it is illegal solution and if so it knows how to fix itself
Knows to calculation the Fitness value according to Evaluation criteria
Knows how to build random and consistent Chromosome
Definition at line 26 of file Chromosome.h.
Constructor & Destructor Documentation
CChromosome::CChromosome () inline
Empty constructor.
Definition at line 32 of file Chromosome.h.
CChromosome::CChromosome (unsigned int iLength, const unsigned int * iSNPs, const BYTE * iGenotypes, double iFitness = DBL_MAX, const vector< string > & iAdditionaFitnesslInfo = vector<string>()) inline
predefined chromosome
Definition at line 45 of file Chromosome.h.
CChromosome::CChromosome (unsigned int iSNP, BYTE iGenotypes = 2, double iFitness = DBL_MAX, const vector< string > & iAdditionaFitnesslInfo = vector<string>()) inline
predefined chromosome of length 1
Definition at line 73 of file Chromosome.h.
CChromosome::CChromosome (const CChromosome & input) inline
Copy constructor.
Definition at line 86 of file Chromosome.h.
References mGenotypes, and mSNPs.
virtual CChromosome::~CChromosome () inline virtual
Destructor.
Definition at line 101 of file Chromosome.h.
Member Function Documentation
const vector<string>& CChromosome::AdditionalFitnessData () const inline
Definition at line 147 of file Chromosome.h.
Referenced by operator<<().
virtual CChromosome& CChromosome::Assignment (const CChromosome & input) inline virtual
Assignment operator.
Reimplemented in CChromosomeMooney, and CChromosomeYang.
Definition at line 113 of file Chromosome.h.
double CChromosome::Fitness () const inline
Definition at line 124 of file Chromosome.h.
Referenced by operator<<().
void CChromosome::Fitness (double input) inline
Definition at line 127 of file Chromosome.h.
static uint64_t CChromosome::FitnessCalculationCounter () inline static
Definition at line 134 of file Chromosome.h.
Referenced by CPostProcessingAlg::Execute().
unsigned int CChromosome::Genotype (unsigned int index) const inline
Definition at line 139 of file Chromosome.h.
Referenced by operator<<().
void CChromosome::Genotype (unsigned int index, BYTE iValue) inline
Definition at line 142 of file Chromosome.h.
BYTE* CChromosome::Genotype () const inline
Definition at line 145 of file Chromosome.h.
static void CChromosome::Init (unsigned int iLength) static
unsigned int CChromosome::Length () const inline
Definition at line 136 of file Chromosome.h.
Referenced by operator<<().
bool CChromosome::operator< (const CChromosome & input) const inline
Definition at line 210 of file Chromosome.h.
References mFitness.
CChromosome& CChromosome::operator= (const CChromosome & input)
Assignment operator.
Referenced by CChromosomeMooney::operator=().
bool CChromosome::operator== (const CChromosome & input) const inline
Comparison operator.
Definition at line 220 of file Chromosome.h.
References mGenotypes, and mSNPs.
bool CChromosome::operator== (const vector< unsigned int > & input) const inline
Definition at line 225 of file Chromosome.h.
bool CChromosome::operator> (const CChromosome & input) const inline
Definition at line 215 of file Chromosome.h.
References mFitness.
void CChromosome::ReplaceGenotype (BYTE & c1, BYTE & c2) inline static protected
Replace the value of 2 Genotypes.
Parameters
[out] c1 first Genotype to replace.
[out] c2 second Genotype to replace.
Definition at line 203 of file Chromosome.h.
void CChromosome::ReplaceSNP (unsigned int & c1, unsigned int & c2) inline static protected
Replace the value of 2 SNPs.
Parameters
[out] c1 first SNP to replace.
[out] c2 second SNP to replace.
Definition at line 196 of file Chromosome.h.
static unsigned int CChromosome::RequiredLength () inline static
Definition at line 132 of file Chromosome.h.
unsigned int CChromosome::SNP (unsigned int index) const inline
Definition at line 138 of file Chromosome.h.
Referenced by operator<<().
void CChromosome::SNP (unsigned int index, unsigned int iValue) inline
Definition at line 141 of file Chromosome.h.
const unsigned int* CChromosome::SNP () const inline
Definition at line 144 of file Chromosome.h.
Member Data Documentation
vector<string> CChromosome::mAdditionalFitnessData protected
Additional Fitness information.
Definition at line 171 of file Chromosome.h.
bool CChromosome::mFitenssValid protected
true iff the object's contents has been changed from the last fitness calculation.
Definition at line 168 of file Chromosome.h.
double CChromosome::mFitness protected
Fitness of current object.
Definition at line 165 of file Chromosome.h.
Referenced by operator<(), and operator>().
BYTE* CChromosome::mGenotypes protected
Genotype of each SNP {1,2,3}.
Definition at line 162 of file Chromosome.h.
Referenced by CChromosome(), and operator==().
unsigned int CChromosome::mLength protected
Chromosome current length (number of SNPs)
Definition at line 156 of file Chromosome.h.
unsigned int* CChromosome::mSNPs protected
Chromosome's SNPs.
Definition at line 159 of file Chromosome.h.
Referenced by CChromosome(), and operator==().
uint64_t CChromosome::sFitenssCalculationCounter static protected
Definition at line 173 of file Chromosome.h.
unsigned int CChromosome::sLength static protected
Chromosome required length (number of SNPs)
Definition at line 153 of file Chromosome.h.
The documentation for this class was generated from the following file:
Chromosome.h