GA - Yang: Chromosome.h File Reference
Chromosome.h File Reference
#include "GenotypeData.h"
#include "ConfigParams.h"
#include <random>
#include <float.h>
#include <assert.h>
#include <string.h>
Classes
class CChromosome
CChromosome is one element in GA population.
struct CChromosomeSerializer
CChromosome serializer.
Functions
std::ostream & operator<< (std::ostream &out, const CChromosomeSerializer &iSerializer)
Function Documentation
std::ostream& operator<< (std::ostream & out, const CChromosomeSerializer & iSerializer) inline
Definition at line 241 of file Chromosome.h.
References CChromosome::AdditionalFitnessData(), CChromosome::Fitness(), CChromosome::Genotype(), CChromosome::Length(), CChromosomeSerializer::mChromosome, CChromosomeSerializer::mData, CChromosome::SNP(), and CGenotypeData::TotalCase().