GA - Yang: EvolutionaryComputing::CPopulation Class Reference
EvolutionaryComputing::CPopulation Class Reference
#include "Population.h"
Classes
struct GenerationFitness
Private Member Functions
public struct
EvolutionaryComputing::CPopulation::GenerationFitness CPopulation ()
public void Init ()
public void NextGeneration ()
private void Altruism (ref CSolution[] ioNewGeneration)
private CSolution RouletteWheelSelection (ref Random random)
private void Vibrate (ref Random random)
private void Fitness ()
Private Attributes
public double AltruismRate
private CSolution[] mGeneration
private double mAltruismRate = 0.05
private double mCrossoverRatio = 0.75
private double mMutationRatio = 0.03
private uint mFixationCounter = 0
private uint mFixationLimit = 10000
private double mChangeInFixation = 0
private bool mMutationAppliesToSolution = false
private List< GenerationFitness > mGenerationsFitness
Detailed Description
Definition at line 17 of file Population.h.
Constructor & Destructor Documentation
public struct EvolutionaryComputing::CPopulation::GenerationFitness EvolutionaryComputing::CPopulation::CPopulation () inline private
Definition at line 34 of file Population.h.
Member Function Documentation
private void EvolutionaryComputing::CPopulation::Altruism (ref CSolution[] ioNewGeneration) inline private
Definition at line 124 of file Population.h.
References mAltruismRate, and mGeneration.
Referenced by NextGeneration().
private void EvolutionaryComputing::CPopulation::Fitness () inline private
Definition at line 176 of file Population.h.
References mGeneration, and mGenerationsFitness.
Referenced by Init(), and NextGeneration().
public void EvolutionaryComputing::CPopulation::Init () inline private
Definition at line 42 of file Population.h.
References Fitness(), mGeneration, and mGenerationsFitness.
public void EvolutionaryComputing::CPopulation::NextGeneration () inline private
Definition at line 72 of file Population.h.
References Altruism(), Fitness(), mAltruismRate, mCrossoverRatio, mGeneration, mMutationAppliesToSolution, mMutationRatio, RouletteWheelSelection(), and Vibrate().
private CSolution EvolutionaryComputing::CPopulation::RouletteWheelSelection (ref Random random) inline private
Definition at line 134 of file Population.h.
References mGeneration, and mGenerationsFitness.
Referenced by NextGeneration().
private void EvolutionaryComputing::CPopulation::Vibrate (ref Random random) inline private
Definition at line 153 of file Population.h.
References mChangeInFixation, mFixationCounter, mFixationLimit, mGeneration, and mGenerationsFitness.
Referenced by NextGeneration().
Member Data Documentation
public double EvolutionaryComputing::CPopulation::AltruismRate private
Definition at line 194 of file Population.h.
private double EvolutionaryComputing::CPopulation::mAltruismRate = 0.05 private
Definition at line 251 of file Population.h.
Referenced by Altruism(), and NextGeneration().
private double EvolutionaryComputing::CPopulation::mChangeInFixation = 0 private
Definition at line 256 of file Population.h.
Referenced by Vibrate().
private double EvolutionaryComputing::CPopulation::mCrossoverRatio = 0.75 private
Definition at line 252 of file Population.h.
Referenced by NextGeneration().
private uint EvolutionaryComputing::CPopulation::mFixationCounter = 0 private
Definition at line 254 of file Population.h.
Referenced by Vibrate().
private uint EvolutionaryComputing::CPopulation::mFixationLimit = 10000 private
Definition at line 255 of file Population.h.
Referenced by Vibrate().
private CSolution [] EvolutionaryComputing::CPopulation::mGeneration private
Definition at line 248 of file Population.h.
Referenced by Altruism(), Fitness(), Init(), NextGeneration(), RouletteWheelSelection(), and Vibrate().
private List<GenerationFitness> EvolutionaryComputing::CPopulation::mGenerationsFitness private
Definition at line 260 of file Population.h.
Referenced by Fitness(), Init(), RouletteWheelSelection(), and Vibrate().
private bool EvolutionaryComputing::CPopulation::mMutationAppliesToSolution = false private
Definition at line 257 of file Population.h.
Referenced by NextGeneration().
private double EvolutionaryComputing::CPopulation::mMutationRatio = 0.03 private
Definition at line 253 of file Population.h.
Referenced by NextGeneration().
The documentation for this class was generated from the following file:
Population.h